#!/usr/bin/env bash
INPUT_FILE='/home/manohar/Desktop/studies/sem7/netwroks/Lab33/142201034_112201034_Lab3/A/Client_Thread/inputs'
OUTPUT_FILE='/home/manohar/Desktop/studies/sem7/netwroks/Lab33/142201034_112201034_Lab3/A/Client_Thread/outputs'

./client localhost 1234 <"$INPUT_FILE/Dostoyevsky.txt" >"$OUTPUT_FILE/dual-c1.out" 2>&1 &
./client localhost 1234 <"$INPUT_FILE/Dostoyevsky.txt" >"$OUTPUT_FILE/dual-c2.out" 2>&1 &
wait
echo "Client outputs saved to $OUTPUT_FILE"